language: node_js
node_js:
- '4'
- '5'
- '6'
matrix:
  fast_finish: true
before_deploy:
- npm prune --production
- tar -czvf pactinterceptor.tar.gz src test package.json CHANGELOG.md README.md LICENSE
deploy:
- provider: releases
  api_key:
    secure: pHMLSqplXSOdWjsETwvVOBvEAB5tOVrWUSpjOQ8chBpfzySko9wHmlAlpg5WlcygUxL6JI9H71IZq+FStyMofqA83gZ6Ehp+R5SufAsG+Ud450M1lR8laSdpA0EpLTB+fxnYTtX7+MXqvj2OFjLFz8cnZa58xRQBUE0ZUl6q+zo9c9NqS0sf+ltbnqNsIxMbNoY3anUQRgFvQkrebDw1sbC9f8ARCASfyHJHNGxHvQP3NQsS9kavFvxYQ8BQIfuWK9GZwTOBexWYRKGjB13nPVVL2B0lqyXd7isX/H6SpN8e3nGl/9nXr5KXF0Dqs/1lgHha5MTzc684duvlfEXrQXueXREGgU3Se8y9ZU2j6XvJyPDPK9FLRRCkjB1N8JtDDXaYRbO58U5gt3RprTnZt7v9xvOHpPCW3IHOmnEBYgYUQPWx2tCNqFiH3HqPzYUrfwCgDaW0MOlvytUlFU3ZHAy1dV9qebYK5SSPaDwf1sM4Y8LSOO3UrWDM/CEMSlXa+dmxnq5WWYkF2z93Qfi+z2vJ8jAli1rnX0TUMxi/jWLyQzpAz2yvIr5X+buklhHaLPJmt/M40ET4NET+GU+Dwf9ZXA/5KRjhQhJnQ8QKV4HEBSwlNC1eiM9pu6YHjTnHFASc7xwtwkCeJjSw3m92jLNwSCxLz80K2/0wgRFaSBw=
  file: pactinterceptor.tar.gz
  skip_cleanup: true
  on:
    tags: true
    node: '6'
- provider: npm
  email: tarcio@gmail.com
  api_key:
    secure: KQG0dUDJrID1rPNwvuHxcH8+YCQcchCcOOpmsIR/JaB4rpJLNLQ6CVc2oC60jArXXBGTWfX777JdDmnBb6XX9IBmAZBVpKginjHxAk988rcjJyhhZROrhkUZiIKSal7f5rdNgF9B2pWJn0mAOUYvHADjm/BcFr3BxTP44a0S0SJXp8ZgtvpzvRQtS/YrUsIdorS0q5ZvOsF7pjhKFIJHLbzSLxfYe6meH34g9UAWullkjY1z2r1rywfqGGaWhLkD8/93kblI+mphYP48aI3nrR5t4zockR6rajzK7pMRfvAjqzXEJj+QHIEle1En2uCCVVvbKVywfvG07w92parYj+oZgWmzPYELvvgUHsV2sTe9rVCUH7ZqQY8VlQLxYmLAoBSiop8tEmIPCm/k+G4rdqcKjuvooXkzNYV8o3N061QnsMae/dZcFn6i1SgaP0GOCTXkvZCXBwEG5Oy/tcdiWX7w+R46m5IqjbALk9B0FhTNnM9YzvE2wtciWfOQaPTRdxFj94CWngBRRmk8cawvpaSHbhrpfuS63dbmF6aIUMvxSPGpgUaOg0siv13yvRAsQViVSHvj8FP6EgaR8XuK3LYocavSEhYwS4t6zE6QLCdfO2ruDnkYsbAx59iJf2LlUY0Z9tIHOiFIi6jFxHz0ROGUWoCDjVb2ydH6SZukThY=
  skip_cleanup: true
  on:
    tags: true
    node: '6'
