language: node_js
node_js:
- '4'
- '5'
- '6'
matrix:
  fast_finish: true
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: ju30KDpSYrw+nd2MmZTOjCTJu+gFNDy9auc6h/K9HhWgGX9zQ2cX0Vq4LX5EHWCImyPoVuyuxiouHoWB/eYcDtyDUoXb+EzNn/i+JXVWteQVRdbgnbDNHccGIpMYwEBrslg+iZWz5/SuxeqB/R0jd7MDK6oQBhWKAXgEYNOBEnRh814jryf93gQc8s4gONq2QoSiFk5QwDfqbvoK2o/4RsGGu3YBxy9/O8LhPTiI9YpdtjxmQtdgbchXLU0/oxv/7P/Etc5Z/0uqRwuF6YMZhJE6FT4ytLCDjaldYyMUAQ2YCT13UfouOO2gZYG0w+zpVGJ+e0hi/+6y1BCew/qNwTylMapcMpMCOsc2XLLD0HZoDrYprx8nUjZd0X859Rod+AWWEQnUhtFR7vqv69zwaH5TFR6l9uh+TragdgWUhJvWvupl1i26JBh0G1dFfWaU+rK/bmcsHK2ioPz2Ij+XrEdJV4KFtc7HPDWV1nCmiX5LA+cypDdfCNQehIufe6gArUUsV/vwtyEkTeOwzJAFgvOgufeZSivhttm/loalD1kX1JLrdR1ebxARvK2zSszeBYlFBwGCuK6sWup5Ace5TX39Ff6TRyO3YCTzaOd6k4w+Fsk93SkKLhGrDby21yIcmrkPdpDLjvR70SLb+OepemISktQpeMPrBTdfQU3J5G4=
before_deploy:
- npm prune --production
- tar -czvf pactinterceptor.tar.gz src package.json README.md LICENSE
deploy:
- provider: releases
  api_key:
    secure: gPWLWI14nYnPT9VoEQPXkrsYrMl0ai/nB5Ys6OaUay4WD/xqFZq9tEszrSqFfrZZpRFNpgyAO3Q2gAVkfpVVIxsDBYXUh4dfQLbab76Ev7XSaHUWdqZdJHq2T/sXMMA8qop1HBjtylJor23/aPHXGEEumk776duPILQ3gEunAEGQjbHvnhREnDkwJNvKVqeefym4oYA2kwSHzUEuf+Y1XUJZgJ6eoAXaZ2+wg4LlPVBEq/bm0G/73m/Ll4q1JPNPREOffMOZQ2HawuFO3IRb4T8B6ZHre1MBCsnLGh3ruP8ZJiUtMA9xddru40QaZsu43Bi8HX9fMH+06mOSvAmqVUDInyGqZjjQYzFTLuaBtWK9wkuqT+uoCjX7pkGFdpHUPhRqpGBI2CiApA67M2K9A9HGUOCQCmN2mgFpeAe6tN04AeoIfv4mcTMImdWMav2/N7XHaraTb6oP9B7IiE9jOYGJ+HIlanp6eTjsghD/ZxCRefHdi0fUAjOuRs6BrIDSJjU5iTzghbWRPTyZso+PPUhLIko0Z9v2IhKMAqJzpXpoxLxVufmrn5sFs8rKHWE2rkBsjofXsmdVC7eC2LrdhWRUvKsnWgprnkJ8afxUdCC/cqS/cdIp6NHdmMaHFR4FT00pdMim3S+XGeoXLDXS2yVhP7NEdr3QIJa3wVTot9I=
  file: pactinterceptor.tar.gz
  skip_cleanup: true
  on:
    tags: true
    node: '6'
- provider: npm
  email: "tarcio@gmail.com"
  api_key:
    secure: KgY7CzHE8ZoMh0aYCG/bIw2W2PWn9gnprbah7fRYq5Iia0EyH2ZGkQCcJNrUetODuDPV5r4Yr+v6FaNmd4TvQZfSoUFXJMW2k98lN3riFVuph6o7XksB6FSqxyf7oZ19RUjs9SmzADJTmLjQIHkQB0lmrf4yiR2OhuEsKsJQB4pGCv0+q/2DBloqapByu1vijPskMtvYdbyvV7k06LzLTmf7Kh6zSBJtL4Ip5LL2hjiAHVU36lYzmd+BeEbhUlPLAjfAHQtwRiQrmAYMGYoppmhiCfrP7EyBJ9XS9p8j+EEON/K9vKoqD5Mhxff57Ou+YNXaIJXAOLpFzJc2OgiKsNTPQZmuZlObuUMA0ah71cWfr7UyHgHq7OXIP+mxBo6onGCETYhZwcj3T8cHOmX8yv6WQueT5ccbuY8Lo413SAVapQcGwWVS1T2Ibe+F0wPi/RWhrLHVS8/hbHl7VT2EGoIKrZCicuKjsv6kciUM9W/MsUj256NVOAIw+Gt8/JbzxrMVUs2miWRLCGaFr8X2ML71IJY2XBpBalA6ej3ZEVEhCzdBIivCvZ06Td8LEEVoZtcxrXODNnt3LM1vDWyNhZMZOzK4BoCIDE5JPubMfpGjL/urEBZzONdOyL/07uKRMMdTHtz+dj5FjSC7OSK9YNe5JBFzO1aTXbNXftAwAzs=
  file: pactinterceptor.tar.gz
  skip_cleanup: true
  on:
    tags: true
    node: '6'
